### ISSUE TITLE
Migrate to EventStreams (SSE)

### ISSUE THREAD

**Issue by Krinkle** [streamreasoning/TripleWave#20]
Hi,

Wikimedia is planning to decommission the socket.io based RCStream in July this year.
A new service called EventStreams is available in its place.

* https://blog.wikimedia.org/2017/03/20/eventstreams/
* https://wikitech.wikimedia.org/wiki/EventStreams
* https://phabricator.wikimedia.org/T156919

**Comment by janez87** [comment]
Hi,
thank you for the news!
We will migrate to EventStream ASAP.

Andrea

**Comment by ottomata** [comment]
Just a reminder that we will be deprecating RCStream in a few weeks.  The deadline for switchover is July 7th!

**Comment by dellaglio** [comment]
Hi @ottomata, thank you very much for the reminder! 
We have already developed the new connector, and we are goin to push it in the master branch in the next weeks.
